export default {
  content: [
    "./app.vue",
    "./components/**/*.vue",
    "./pages/**/*.vue",
    "./vueform.config.ts",
    "./node_modules/@vueform/vueform/themes/tailwind/**/*.vue",
    "./node_modules/@vueform/vueform/themes/tailwind/**/*.js",
  ],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },
  safelist: [
    { pattern: /bg-.*/ },
    { pattern: /btn-.*/ },
    { pattern: /badge-.*/ },
    { pattern: /text-.*/ },
  ],
}
